// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCeuR7rxVqlnXVdQhti4V6UOOU510UpOc',
    appId: '1:449679109705:android:50b98cde25cb4638155998',
    messagingSenderId: '449679109705',
    projectId: 'zoomart-30f24',
    databaseURL: 'https://zoomart-30f24-default-rtdb.firebaseio.com',
    storageBucket: 'zoomart-30f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbjhnLCliFzpVEK1M217wXImWfVb3emA',
    appId: '1:449679109705:ios:850a6a64ad39aafb155998',
    messagingSenderId: '449679109705',
    projectId: 'zoomart-30f24',
    databaseURL: 'https://zoomart-30f24-default-rtdb.firebaseio.com',
    storageBucket: 'zoomart-30f24.appspot.com',
    iosClientId: '449679109705-n3ea4ncbm7mvh0m8t1atf60as6dilkji.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbjhnLCliFzpVEK1M217wXImWfVb3emA',
    appId: '1:449679109705:ios:850a6a64ad39aafb155998',
    messagingSenderId: '449679109705',
    projectId: 'zoomart-30f24',
    databaseURL: 'https://zoomart-30f24-default-rtdb.firebaseio.com',
    storageBucket: 'zoomart-30f24.appspot.com',
    iosClientId: '449679109705-n3ea4ncbm7mvh0m8t1atf60as6dilkji.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomart',
  );
}
